# Generated by Django 6.0.7 on 2026-08-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('coach_name', models.CharField(max_length=200, verbose_name='coach')),
                ('main_phone_number', models.CharField(max_length=20, verbose_name='main phone')),
                ('extra_phone_number', models.CharField(blank=True, max_length=20, verbose_name='extra phone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='category name')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum player age')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='required gender')),
                ('allows_mixed_gender', models.BooleanField(default=False, verbose_name='allows mixed-gender teams')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('event_type', models.CharField(choices=[('tournament', 'Tournament'), ('open', 'Open event')], max_length=20, verbose_name='event type')),
                ('date', models.DateField(verbose_name='event date')),
                ('time', models.TimeField(verbose_name='event time')),
                ('registration_deadline', models.DateTimeField(verbose_name='registration deadline')),
                ('max_teams', models.PositiveSmallIntegerField(default=16, verbose_name='max teams')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.club', verbose_name='location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.teamcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.BooleanField(verbose_name='team type (basketball / streetball)')),
                ('name', models.CharField(max_length=50, verbose_name='team name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of_teams', to='users.profile', verbose_name='captain')),
                ('category', models.ManyToManyField(related_name='teams', to='core.teamcategory', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points1', models.PositiveSmallIntegerField(default=0, verbose_name='team 1 score')),
                ('points2', models.PositiveSmallIntegerField(default=0, verbose_name='team 2 score')),
                ('is_finished', models.BooleanField(default=False, verbose_name='game status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='core.team', verbose_name='team 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='core.team', verbose_name='team 2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_cat', to='core.teamcategory', verbose_name='match category')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='RegToTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payment status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.event', verbose_name='event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_registrations', to='core.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'unique_together': {('event', 'team')},
            },
        ),
    ]
