# Generated by Django 6.0.7 on 2026-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcategory',
            name='allows_mixed_gender',
            field=models.BooleanField(default=False, verbose_name='allows mixed-gender teams'),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='required gender'),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum player age'),
        ),
    ]
