# Generated by Django 6.0.7 on 2026-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_type',
            field=models.BooleanField(default=True, verbose_name='team type (basketball / streetball)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('other', 'Other')], max_length=20, verbose_name='event type'),
        ),
    ]
