# Generated by Django 6.0.7 on 2026-08-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of_teams', to='users.profile', verbose_name='captain'),
        ),
        migrations.AddField(
            model_name='regtotournament',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_registrations', to='core.team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='core.team', verbose_name='team 1'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='core.team', verbose_name='team 2'),
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ManyToManyField(related_name='teams', to='core.teamcategory', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_cat', to='core.teamcategory', verbose_name='match category'),
        ),
    ]
