# Generated by Django 6.0.7 on 2026-08-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_team_type_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
    ]
