# Generated by Django 6.0.7 on 2026-08-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_registration_deadline'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, max_length=200, verbose_name='quote')),
                ('is_active', models.BooleanField(default=True, verbose_name='currently featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_of_week_entries', to='users.profile', verbose_name='player')),
            ],
            options={
                'verbose_name': 'Player of the Week',
                'verbose_name_plural': 'Player of the Week',
                'ordering': ['-created_at'],
            },
        ),
    ]
