# Generated by Django 6.0.7 on 2026-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text_content', models.TextField(verbose_name='news text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
    ]
